// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcoixlvbkssvuxamzwvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjb2l4bHZia3NzdnV4YW16d3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzOTYyNzIsImV4cCI6MjA4NDk3MjI3Mn0.BVPwqGMc7RhqRSOjnqIsZjwhe4Ls9pf9aajX-by-98M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});